// Offline support: saves every game file on the first visit, then serves from
// that copy (refreshing it in the background whenever there's a connection).
// VERSION and PRECACHE are generated by tools/build-sw.mjs — rerun it after changing files.
const VERSION = '1d055e95097a';
const PRECACHE = [
  './',
  './assets/models/lab/Cauldron.bin',
  './assets/models/lab/Cauldron.gltf',
  './assets/models/lab/T_Trim_Metal_BaseColor.png',
  './assets/models/monsters/Bee.gltf',
  './assets/models/monsters/Cactus.gltf',
  './assets/models/monsters/Dragon.gltf',
  './assets/models/monsters/Ghost.gltf',
  './assets/models/monsters/Mushroom.gltf',
  './assets/models/monsters/Penguin.gltf',
  './assets/models/monsters/Pig.gltf',
  './assets/models/nature/BirchTree_2.bin',
  './assets/models/nature/BirchTree_2.gltf',
  './assets/models/nature/BirchTree_Bark.jpg',
  './assets/models/nature/BirchTree_Leaves.png',
  './assets/models/nature/Bush_Flowers.bin',
  './assets/models/nature/Bush_Flowers.gltf',
  './assets/models/nature/Bush_Large_Flowers.bin',
  './assets/models/nature/Bush_Large_Flowers.gltf',
  './assets/models/nature/Bush_Leaves.png',
  './assets/models/nature/Flower_3_Clump.bin',
  './assets/models/nature/Flower_3_Clump.gltf',
  './assets/models/nature/Flower_4_Clump.bin',
  './assets/models/nature/Flower_4_Clump.gltf',
  './assets/models/nature/Flowers.png',
  './assets/models/nature/MapleTree_1.bin',
  './assets/models/nature/MapleTree_1.gltf',
  './assets/models/nature/MapleTree_3.bin',
  './assets/models/nature/MapleTree_3.gltf',
  './assets/models/nature/MapleTree_Bark.jpg',
  './assets/models/nature/MapleTree_Leaves.png',
  './assets/models/space/Planet_1.gltf',
  './assets/models/space/Planet_3.gltf',
  './assets/models/space/Planet_6.gltf',
  './assets/models/space/Planet_9.gltf',
  './assets/models/space/Rock_1.gltf',
  './assets/models/space/Rock_Large_2.gltf',
  './assets/models/space/Spaceship_BarbaraTheBee.gltf',
  './assets/models/space/Spaceship_FernandoTheFlamingo.gltf',
  './assets/models/space/Spaceship_FinnTheFrog.gltf',
  './assets/models/space/Spaceship_RaeTheRedPanda.gltf',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './index.html',
  './js/battle.js',
  './js/flight.js',
  './js/fx.js',
  './js/lab.js',
  './js/main.js',
  './js/potions.js',
  './js/state.js',
  './js/words.js',
  './manifest.webmanifest',
  './style.css',
  './vendor/fonts/Andika-mem8Ya6iyW-Lwqg40ZMFVZ0b.woff2',
  './vendor/fonts/Andika-mem_Ya6iyW-LwqgwarYQ.woff2',
  './vendor/fonts/Baloo2-wXKrE3kTposypRyd51jcAA.woff2',
  './vendor/fonts/fonts.css',
  './vendor/three/addons/loaders/GLTFLoader.js',
  './vendor/three/addons/utils/BufferGeometryUtils.js',
  './vendor/three/addons/utils/SkeletonUtils.js',
  './vendor/three/three.module.js',
];
const CACHE = `owr-${VERSION}`;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // no-cache: revalidate with the server so a new version never precaches stale files.
    await cache.addAll(PRECACHE.map(url => new Request(url, { cache: 'no-cache' })));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith('owr-') && k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: true })
      ?? (req.mode === 'navigate' ? await cache.match('./', { ignoreSearch: true }) : undefined);
    const fresh = fetch(req)
      .then(res => {
        if (res.ok && res.type === 'basic') cache.put(req, res.clone());
        return res;
      })
      .catch(() => undefined);
    if (cached) {
      event.waitUntil(fresh);
      return cached;
    }
    return (await fresh) ?? Response.error();
  })());
});
